export const data = {
  hero: {
    name: "Syahrizal Ardana",
    position: "Full-stack Developer",
    desc: "I'm a dedicated Developer with a passion for creating user-friendly web applications since 2019. I specialize in MERN Stack, which I've been mastering since 2021. Let's build something amazing together!",
    timeline: [
      // { year: "2015", event: "SMA N 1 Lingga Utara" },
      // { year: "2018", event: "University Maritime of Raja Ali Haji" },
      // { year: "2023", event: "Work Life!" },
      { year: "2015", event: "High School!" },
      { year: "2018", event: "University!!" },
      { year: "2023", event: "Graduated!!!" },
    ],
  },
  about: {
    experiences: [
      {
        position: "Front-end Developer",
        company: "AIA Singapore",
        start: "Mar 2023",
        end: "Present",
        location: "Batam",
        tasks: [
          "Developed and maintained responsive frontend applications using React.js, Node.js, and Material-UI, improving user satisfaction by 20%.",
          "Collaborated with cross-functional teams to deliver insurance-related applications, ensuring 100% on-time delivery.",
          "Optimized application performance, reducing page load times by 30% across multiple devices.",
          "Managed codebase using Git and Bitbucket, ensuring seamless collaboration and version control.",
        ],
        techStacks: [
          "React.js",
          "Next.js",
          "Node.js",
          "Express.js",
          "MaterialUI",
          "TypeScript",
          "Express.js",
          "MaterialUI",
          "TypeScript",
        ],
      },
      {
        position: "Mobile Developer",
        company: "Infinite Learning Indonesia",
        start: "Sep 2021",
        end: "Jan 2022",
        location: "Batam",
        tasks: [
          "Led end-to-end development of 2 mobile applications.",
          "Collaborated with design teams to implement user-centric solutions, improving app usability by 25%.",
          "Optimized app performance, reducing load times by 40% before client delivery.",
        ],
        techStacks: [
          "React.js",
          "Next.js",
          "Node.js",
          "Express.js",
          "MaterialUI",
          "TypeScript",
          "Express.js",
          "MaterialUI",
          "TypeScript",
        ],
      },
      {
        position: "Frontend Developer",
        company: "PT. Inforsys Indonesia",
        start: "Mar 2021",
        end: "Aug 2021",
        location: "Batam",
        tasks: [
          "Maintained and enhanced SaaS-based ERP software using AngularJS.",
          "Participated in Agile ceremonies, ensuring timely delivery of incremental updates.",
        ],
        techStacks: [
          "React.js",
          "Next.js",
          "Node.js",
          "Express.js",
          "MaterialUI",
          "TypeScript",
          "Express.js",
          "MaterialUI",
          "TypeScript",
        ],
      },
    ],
  },
  tabLink: [
    {
      title: "Hero",
      href: "hero",
    },
    {
      title: "About",
      href: "about",
    },
    {
      title: "Work",
      href: "work",
    },
  ],
  themes: [
    "Abyss",
    "Autumn",
    "Black",
    "Bumblebee",
    "Business",
    "Cupcake",
    "Dark",
    "Dim",
    "Fantasy",
    "Forest",
    "Light",
    "Nord",
    "Retro",
    "Silk",
    "Valentine",
    "Winter",
  ],
};
